language: php
php:
  - '5.2'
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
  - php: 5.2
  - php: hhvm
  - php: nightly

before_script:
  - composer install --dev

script: phpunit --coverage-text